import React,{useState,useRef} from 'react';
import {ArrowDown,ArrowUpRight,LockKeyhole,ShieldCheck,FileCheck2,MoveHorizontal,Check} from '../icons';
import {Kicker,Action,Aperture} from './Common';
const samples=[{label:'来源承诺',value:'由 Provider 签署',detail:'将请求、响应与这笔订单绑定。',Icon:FileCheck2},{label:'验收规则',value:'规则预先锁定',detail:'新鲜度、样本量、置信度字段。',Icon:ShieldCheck},{label:'公开结论',value:'只公开验收结果',detail:'具体标的、价格和盲因子不披露。',Icon:Check}];
export default function Exhibition(){
 const [scan,setScan]=useState(50),[negative,setNegative]=useState(true);const section=useRef(null);const sample=samples[Math.min(2,Math.floor(scan/34))];const Icon=sample.Icon;
 function explore(){section.current?.scrollIntoView({behavior:(matchMedia('(prefers-reduced-motion: reduce)').matches||document.querySelector('.reduce-motion'))?'instant':'smooth'});section.current?.focus({preventScroll:true})}
 return <>
 <section className="hero" aria-labelledby="hero-title"><Aperture priority/><div className="hero-copy"><Kicker>PRIVATE CONTENT. PUBLIC PROOF.</Kicker><h1 id="hero-title">内容不公开，<br/>交付如何验收？</h1><p>让 Agent 的私密交付，有据可验。<span className="hero-explanation">内容留在双方之间，证据可以公开。</span></p><div className="hero-actions"><Action href="#/lab">进入真实演示</Action><button className="text-action" onClick={explore}>探索验收原理<ArrowDown size={16}/></button></div><div className="hero-note"><span>01—03</span> 一次交付，三种确定性。</div></div><span className="object-label">FIG. 01 — THE VERIFICATION APERTURE</span></section>
 <div className="chapter-index" aria-label="三个价值主张">{[['01','私密验收','内容留下，证据穿过。'],['02','违约退款','不合格，也能被证明。'],['03','可携带凭证','带走原件，独立核验。']].map(([n,t,d])=><div key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div><ArrowUpRight size={19} aria-hidden="true"/></div>)}</div>
 <section className="experiment section" ref={section} tabIndex={-1} aria-labelledby="experiment-title"><div className="section-top"><Kicker>01 / PRIVATE ACCEPTANCE</Kicker><span className="capsule">原理演示 · 不执行交易</span></div><div className="section-heading"><h2 id="experiment-title">只让证据穿过。</h2><p>移动验证窗口。你能检查约定，<br/>却始终看不到交付的私密内容。</p></div><div className="inspection"><div className="inspection-private"><LockKeyhole size={20}/><span>PRIVATE CONTENT</span><h3>此处没有<br/>可以窥见的内容。</h3><p>原理演示不加载私密响应。<br/>遮挡只是比喻，保密来自数据边界。</p></div><div className="inspection-public" style={{'--position':`${20+scan*.6}%`}}><div className="window-label"><span>PUBLIC EVIDENCE</span><MoveHorizontal size={19}/></div><div className="scan-output" key={sample.label}><Icon size={28}/><span>{sample.label}</span><h3>{sample.value}</h3><p>{sample.detail}</p></div><div className="scan-rule" aria-hidden="true"/></div></div><div className="scan-control"><label htmlFor="scan">移动验证窗口 <span>来源 → 规则 → 结论</span></label><input id="scan" type="range" min="0" max="100" value={scan} onChange={e=>setScan(Number(e.target.value))} aria-valuetext={sample.label}/><span className="mono">{String(scan).padStart(3,'0')} / 100</span></div><p className="small-note">键盘左右方向键同样可操作。这是概念交互；真实签名与证明将在下一步生成。</p></section>
 <section className="reversal section"><div className="section-top"><Kicker>02 / A VALID PROOF CAN SAY NO</Kicker><span className="capsule">规则不变，交付改变</span></div><div className="reversal-grid"><div><h2>证明有效。<br/><em>仍然可以退款。</em></h2><p>真实的签名，不保证合格的交付。<br/>让可验证的结果，决定钱去哪里。</p><div className="segmented" aria-label="概念交付情境"><button aria-pressed={!negative} onClick={()=>setNegative(false)}>合格数据</button><button aria-pressed={negative} onClick={()=>setNegative(true)}>过期数据</button></div></div><div className="concept-receipt"><div className="receipt-top"><span>ILLUSTRATIVE RECEIPT</span><FileCheck2 size={24}/></div><p className="receipt-small">概念示例 · 非真实结算凭证</p><div className="concept-result" key={String(negative)}><span className="serif">{negative?'退款':'付款'}</span><ArrowUpRight size={48}/></div><dl><div><dt>签名与证明</dt><dd><Check size={16}/>均有效</dd></div><div><dt>验收结论</dt><dd>{negative?'不合格':'合格'}</dd></div><div><dt>约定资金去向</dt><dd>{negative?'退还买方':'支付 Provider'}</dd></div></dl></div></div></section>
 <section className="portable section"><Kicker>03 / EVIDENCE YOU CAN TAKE WITH YOU</Kicker><h2>别只相信界面。<br/>带走证据，重新验证。</h2><div className="portable-bottom"><p>公共凭证包含承诺、签名、证明和结算记录。<br/>任何核验者，都应先确认自己信任的链与合约。</p><Action href="#/lab">亲手运行一次</Action></div><div className="boundary-line"><span>真实 ZK 证明</span><span>合成数据</span><span>本地测试 EVM</span><a href="#/protocol">查看信任边界<ArrowUpRight size={15}/></a></div></section>
 </>
}
