import React,{useEffect,useState,useRef,lazy,Suspense} from 'react';
import {Play,ArrowRight,ArrowUpRight,RotateCcw,LockKeyhole,Eye,Download,LoaderCircle,Copy,Maximize2,Minimize2,Terminal,ShieldCheck,FileCheck2,FileText,Fingerprint,Database,Check,Link2,ChevronRight} from '../icons';
import {useSession} from '../session';
import {api,scenarioLabels,stageLabels,runView,short} from '../model';
import {Kicker,RuleList} from './Common';
const Verifier=lazy(()=>import('./Verifier'));
const chapters=[['合格才付款','按约定规则验收'],['不合格就退款','有效证明支持退款'],['证据带得走','导出凭证，重新核验']];
const titles=[<>看不见数据。<br/>也能验收交付。</>,<>证明有效。<br/>这次仍然退款。</>,<>带走这份凭证。<br/>再验证一次。</>];
export default function Lab(){
 const s=useSession();const [scenario,setScenario]=useState(s.chapter===1?'stale':'valid'),[privateView,setPrivateView]=useState(false),[secret,setSecret]=useState(null),[secretError,setSecretError]=useState(''),[notes,setNotes]=useState(false),[fullscreen,setFullscreen]=useState(false);
 const tabs=useRef([]),session=useRef(s),activeRun=s.run,r=s.receipt,view=runView(activeRun,r);
 session.current=s;
 function chapter(i){if(s.busy)return;if(i<2&&i!==s.chapter)s.setRunId(null);s.setChapter(i);setPrivateView(false);if(i<2)setScenario(i===0?'valid':'stale')}
 useEffect(()=>{const sync=()=>{const current=session.current;if(current.busy)return;const scene=new URLSearchParams(location.hash.split('?')[1]||'').get('scene');if(!scene)return;if(scene==='verify'){current.setChapter(2)}else if(scene==='valid'||scene==='stale'){current.setChapter(scene==='stale'?1:0);setScenario(scene);current.setRunId(null)}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 useEffect(()=>{function key(e){if(e.target.closest('input,textarea,select,[contenteditable=true]')||e.altKey||e.ctrlKey||e.metaKey)return;if(['1','2','3'].includes(e.key)){e.preventDefault();chapter(Number(e.key)-1)}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[s.busy,s.chapter]);
 useEffect(()=>{if(!privateView||!activeRun?.id)return;setSecret(null);setSecretError('');const ac=new AbortController();api(`/api/private/${activeRun.id}`,undefined,ac.signal).then(x=>{if(!ac.signal.aborted)setSecret(x)}).catch(e=>{if(!ac.signal.aborted)setSecretError(e.message)});return()=>ac.abort()},[privateView,activeRun?.id,activeRun?.stage]);
 useEffect(()=>{const update=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update)},[]);
 async function full(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{s.setNotice('可使用浏览器菜单进入全屏。')}}
 async function replay(){try{const d=await api(`/api/receipts/${r.orderId}/replay`,{});s.setNotice(d.blocked?'重复结算已拒绝：这笔订单已经完成结算。':'未观察到预期的重放拦截。')}catch(e){s.setNotice(e.message)}}
 async function copy(){try{await navigator.clipboard.writeText(r.settlement.transactionHash);s.setNotice('完整交易哈希已复制。')}catch{s.setNotice('请在交易详情中选择完整哈希。')}}
 const events=activeRun?.log||[];
 return <section className="lab-page page">
  <div className="stage-toolbar"><span>ZERO-KNOWLEDGE ACCEPTANCE</span><div><button aria-pressed={notes} onClick={()=>setNotes(!notes)}><Terminal size={15}/>讲稿</button><button aria-label={fullscreen?'退出全屏':'进入全屏'} onClick={full}>{fullscreen?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button></div></div>
  <div role="tabpanel" id="chapter-panel" aria-labelledby={`chapter-${s.chapter}`}>
  {s.chapter===2?<><div className="verify-heading"><Kicker>PORTABLE PROOF / 零知识验收凭证</Kicker><h1>{titles[2]}</h1><p>原件可以复验，改动会留下痕迹。</p></div><Suspense fallback={<div className="verification-paper" role="status">正在打开凭证核验器…</div>}><Verifier/></Suspense></>:<div className="demo-canvas">
   <div className="story-column"><Kicker>PRIVATE DATA. PUBLIC PROOF.</Kicker><h1>{titles[s.chapter]}</h1><p className="lead">{s.chapter===0?'Agent 购买数据，按约定验收。通过付款，不合格退款。':'同一套验收规则。换成过期数据，看看资金会流向哪里。'}</p>
    <section className="private-panel" aria-label="私密输入"><div className="panel-label"><span><LockKeyhole size={15}/>PRIVATE INPUT</span><span>内容已封存</span></div><div className="private-content"><label>数据来源</label><div className="provider-label"><Database size={16}/>签名数据 Provider<ChevronRight size={15}/></div><label>私密响应</label><div className="sealed-fields">{['查询标的','行情价格','样本数量','置信度字段'].map(t=><div key={t}><FileText size={14}/><span>{t}</span><LockKeyhole size={12}/><span aria-label="内容保密" className="redacted">••••••••</span></div>)}</div><p className="privacy-foot"><Eye size={16}/><span>内容保密，验收可验证。<small>公共凭证保留证明与结论。</small></span></p></div></section>
   </div>
   <figure className={`object-stage ${s.busy?'working':''}`}><img src="/images/home-envelope.webp" srcSet="/images/home-envelope-600.webp 600w, /images/home-envelope.webp 900w" sizes="(max-width:650px) 300px, (max-width:900px) 340px, 410px" width="900" height="1350" alt="透明玻璃信封以蓝色锁章封存私密数据" fetchPriority="high"/><figcaption><strong>VeilReceipt</strong><span>PRIVATE DATA · PUBLIC PROOF</span></figcaption>{s.busy&&<div className="proof-working"><LoaderCircle className="spin" size={15}/>{stageLabels[activeRun?.stage]||'准备验收'}</div>}</figure>
   <section className={`public-receipt ${view.tone}`} aria-live="polite" aria-busy={s.busy}><div className="panel-label"><span><FileCheck2 size={17}/>PUBLIC PROOF</span><span>{r?`#${r.orderId.padStart(4,'0')}`:'可公开验证'}</span></div>
    <div className="receipt-main"><span className="result-icon">{s.busy?<LoaderCircle size={32} className="spin"/>:r?<Check size={34}/>:<Fingerprint size={31}/>}</span><div><h2>{view.title}</h2><p className="settlement-amount">{r?.amount||'0.002'} <span>测试 ETH</span></p></div></div><p className="verdict-detail">{view.detail}</p>
    <div className="evidence-rows"><span className="evidence-caption">验收证据</span>{[[ShieldCheck,'零知识证明',view.proof],[FileCheck2,'服务验收',view.acceptance],[Database,'资金结算',view.money]].map(([Icon,title,value])=><div key={title}><span className="evidence-icon"><Icon size={17}/></span><div><strong>{title}<b>{value}</b></strong><small>{title==='零知识证明'?(r?`本次生成 ${(r.metrics.proveMs/1000).toFixed(2)} 秒`:'根据私密内容生成可验证证明'):title==='服务验收'?'按订单中预先约定的规则':'资金结果以交易确认记录为准'}</small></div>{r&&<Check size={14}/>}</div>)}</div>
    {r?<><button className="tx-chip" onClick={copy}><Link2 size={17}/><span>结算交易<code>{short(r.settlement.transactionHash)}</code></span><Copy size={15}/></button><div className="receipt-actions"><button onClick={()=>chapter(2)}>带走并核验<ArrowUpRight size={16}/></button><a download href={`/api/receipts/${r.orderId}`} aria-label="下载当前公共凭证"><Download size={18}/></a></div></>:activeRun?.status==='blocked'&&activeRun.orderId?<button className="action secondary" disabled={s.busy||s.connection!=='online'} onClick={s.expire}><RotateCcw size={16}/>演示到期退款</button>:<p className="receipt-bottom-note">{activeRun?.status==='expired'?'到期退款已确认。':'开始后，将在这里生成验收凭证。'}</p>}
   </section>
  </div>}
  </div>
  <div className="stage-dock"><div className="chapter-tabs" role="tablist" aria-label="演示章节">{chapters.map(([title,subtitle],i)=><button ref={el=>tabs.current[i]=el} key={title} id={`chapter-${i}`} role="tab" aria-selected={s.chapter===i} aria-controls="chapter-panel" tabIndex={s.chapter===i?0:-1} disabled={s.busy} onClick={()=>chapter(i)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;chapter(n);tabs.current[n]?.focus()}}}><span className="chapter-number">0{i+1}</span><span><strong>{title}</strong><small>{subtitle}</small></span></button>)}</div>
   <div className="dock-action">{s.chapter<2?<><label className="scenario-select"><span className="sr-only">交付情境</span><select aria-label="交付情境" value={scenario} disabled={s.busy} onChange={e=>{setScenario(e.target.value);s.setRunId(null);setPrivateView(false)}}>{Object.entries(scenarioLabels).map(([v,k])=><option key={v} value={v}>{k}</option>)}</select></label><button className="action run-button" disabled={s.busy||s.connection!=='online'} onClick={()=>{setPrivateView(false);s.launch(scenario)}}>{s.busy?<LoaderCircle size={17} className="spin"/>:<Play size={17}/>} {s.busy?'真实验收中':'运行真实验收'}<ArrowRight size={18}/></button></>:<button className="action secondary" onClick={()=>chapter(0)}><RotateCcw size={17}/>重新演示</button>}</div>
  </div>
  {activeRun&&s.chapter<2&&<div className="execution-trail" aria-live="polite"><span className={`run-status ${activeRun.status}`}>{view.title}</span><span>{events.at(-1)?.text}</span></div>}
  {s.chapter<2&&<div className="lab-details"><details><summary>查看验收规则</summary><RuleList/><p>同时检查标的一致与价格大于零。阈值针对 Provider 签署的字段，新鲜度以订单参考时间计算。</p></details><details><summary>执行记录与交易证据</summary>{activeRun?<><ol className="event-log">{events.map((l,i)=><li key={i}><time>{new Date(l.at).toLocaleTimeString('zh-CN',{hour12:false})}</time>{l.text}</li>)}</ol>{r&&<><p>证明 {(r.metrics.proofBytes/1024).toFixed(1)} KiB · 区块 #{r.settlement.blockNumber}</p><code>{r.settlement.transactionHash}</code><div className="inline-actions"><button onClick={copy}><Copy size={15}/>复制交易哈希</button><button onClick={replay} disabled={s.busy}><RotateCcw size={15}/>尝试重复结算</button></div></>}{activeRun.refundTx&&<code>{activeRun.refundTx}</code>}</>:<p>运行验收后，这里显示实际记录。</p>}</details><details><summary>本机私密样本</summary><p>合成数据 · 仅在点击后加载本机买方样本。</p><button className="text-action" aria-pressed={privateView} onClick={()=>setPrivateView(!privateView)} disabled={!activeRun}><Eye size={17}/>{privateView?'隐藏样本':'查看本机样本'}</button>{privateView&&(secret?<dl className="rule-list"><div><dt>标的</dt><dd>{secret.asset}</dd></div><div><dt>价格</dt><dd>${(secret.price_micros/1e6).toFixed(2)}</dd></div><div><dt>样本量 / 置信度</dt><dd>{secret.sample_count} / {secret.confidence_bps/100}%</dd></div></dl>:<p>{secretError||'正在加载样本…'}</p>)}</details></div>}
  {notes&&<aside className="speaker-notes"><Kicker>SPEAKER NOTES / 第 {s.chapter+1} 幕</Kicker><p>{['Agent 买到一份付费数据。第三方如何确认它符合约定，同时保留内容隐私？现在运行合格交付，观察证明、验收和付款三个结果。','保持规则不变，换成过期数据。来源签名有效，证明也有效，但验收不合格，因此款项退回买方。','把刚才的凭证导出并重新核验。原件通过；只改验收结论的副本被拒绝。证据可以离开原页面，被再次检查。'][s.chapter]}</p><span>快捷键 1 / 2 / 3 切换章节。</span></aside>}
  <section className="home-intro"><div className="home-intro-title"><div><Kicker>WHY VEILRECEIPT</Kicker><h2>一笔私密交易，<br/>留下三份确定的依据。</h2></div><a href="#/story" className="text-action">了解完整故事<ArrowUpRight size={18}/></a></div><div className="home-benefits">{[[LockKeyhole,'私密验收','以零知识证明验证约定条件，保留具体交付内容。'],[RotateCcw,'按约结算','有效验收证明连接付款与退款，资金去向有据可查。'],[FileCheck2,'凭证可复验','导出承诺、签名、证明与交易记录，交给核验工具重新检查。']].map(([Icon,title,desc],i)=><article key={title}><span className="benefit-index">0{i+1}</span><Icon size={24}/><h3>{title}</h3><p>{desc}</p></article>)}</div><div className="tech-strip"><span>BUILT WITH</span><b>Noir</b><b>UltraHonk</b><b>Poseidon2</b><b>EIP-712</b><b>Solidity</b></div></section>
 </section>
}
