import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,ArrowUpRight,LockKeyhole,ShieldCheck,FileCheck2,Clock3,Database,Check,Fingerprint,Wallet,Braces,Download,X,Eye,Maximize2,Link2} from '../icons';
import './Story.css';
const chapters=[
 {short:'一笔交易',en:'THE PRIVATE DELIVERY',tone:'paper',title:['看不见数据，','也能验收交付。'],body:'Agent 买下一份付费行情。\n数据已交付，款项正等待验收。',bridge:'收到响应之后，外部核验者依据什么决定付款？',next:'验收的难题'},
 {short:'验收难题',en:'THE ACCEPTANCE QUESTION',tone:'paper',title:['验收需要看内容，','内容却是商品。'],body:'买方已经拿到原文。\n合约与其他核验者，还需要独立的验收依据。',bridge:'能否保留原文，只公开验收证据？',next:'零知识方案'},
 {short:'零知识方案',en:'PRIVATE INPUT. PUBLIC PROOF.',tone:'lavender',title:['内容留在私域，','证据走向公开。'],body:'VeilReceipt 用零知识证明，\n证明这份交付是否满足订单约定。',bridge:'有了证明，它怎样进入一笔完整交易？',next:'看完整流程'},
 {short:'服务流程',en:'FROM ORDER TO SETTLEMENT',tone:'paper',title:['一笔订单，','如何走到结算？'],body:'规则、交付、证明与资金，各有清晰的去向。',bridge:'怎样确认这些证据属于同一笔交付？',next:'理解技术连接'},
 {short:'技术连接',en:'ONE ORDER. ONE COMMITMENT.',tone:'paper',title:['同一笔订单，','绑定同一份交付。'],body:'内容承诺、来源签名、验收证明，共同指向已锁定的订单规则。',bridge:'回到订单 A，实际验收一次合格交付。',next:'合格，付款'},
 {short:'合格付款',en:'ACCEPTED & PAID',tone:'paper',title:['这份交付合格，','款项按约支付。'],body:'回到订单 A：私密内容完成验收，\n托管款支付给数据 Provider。',bridge:'如果规则不变，交付换成过期数据呢？',next:'下一笔，过期数据'},
 {short:'有效退款',en:'VALID PROOF. REFUNDED.',tone:'paper',title:['证明有效，','这次却退款。'],body:'规则保持不变，订单 B 换成过期数据。\n有效的证明，也能给退款提供依据。',bridge:'把这份退款凭证交出去，别人还能重新核验吗？',next:'带走凭证'},
 {short:'凭证复验',en:'EVIDENCE THAT TRAVELS',tone:'paper',title:['凭证离开页面，','验证仍然继续。'],body:'导出订单 B 的退款凭证。\n原件通过；仅修改验收结果的副本被拒绝。',bridge:'如果证据能离开原应用，哪些系统可以继续使用它？',next:'公共能力'},
 {short:'公共能力',en:'BUILD ON SHARED EVIDENCE',tone:'sage',title:['一份交付证据，','成为更多系统的输入。'],body:'从一张可复验的凭证，走向可复用的验收能力。\n其他开发者也能接入自己的 Agent 与数据服务。',bridge:'回到最初的问题：这笔交易最终留下了什么？',next:'回到这笔交易'},
 {short:'亲手验证',en:'PRIVATE DELIVERY. PUBLIC EVIDENCE.',tone:'paper',title:['让私密交付，','留下可验证的凭证。'],body:'谁承诺、按什么规则、验收如何、钱到哪里。\n一笔交易，留下完整证据。',bridge:'内容保密，验收与结算留下证据。',next:'回到开场'}
];
const flow=[
 ['买方 → 合约','锁定规则与托管款','创建订单，固定验收规则和请求承诺，存入 0.002 测试 ETH。'],
 ['买方 → Provider','发起请求','请求关联订单标识，双方使用同一套约定。'],
 ['Provider → 买方','私密交付与签名','原始响应交给买方；Provider 对交付承诺签名。'],
 ['买方侧证明程序','生成零知识证明','读取私密输入，按订单规则计算验收结论。'],
 ['买方 → 合约','提交公开证据','提交承诺、签名、证明与结论，不提交原始响应。'],
 ['验证与托管合约','验证并结算','核对订单、签名与证明。有效证明验收通过则付款，不通过则退款。'],
 ['买方 → 外部核验者','导出公共凭证','携带订单、承诺、签名、证明和结算记录。'],
 ['外部核验者 → 合约','独立复验','结合可信链与合约信息，重新检查交付证据。']
];
const technologies=[
 ['Poseidon2','内容承诺','私密请求与响应生成带随机盲因子的承诺；电路重新计算，检查使用的是同一份内容。',Database],
 ['EIP-712','来源承诺','Provider 对订单及内容承诺签名，合约核对由谁认领这次交付。',Fingerprint],
 ['Noir · UltraHonk','验收证明','电路计算内容是否满足规则，证明与公开输入一起送交验证器。',Braces],
 ['Solidity','验证与结算','使用已保存的订单规则验签、验证证明，并执行一次付款或退款。',Wallet]
];
function currentChapter(){const n=Number(new URLSearchParams(location.hash.split('?')[1]||'').get('chapter'));return Number.isInteger(n)&&n>=1&&n<=10?n-1:0;}
function Art({name,alt,className='',eager=false}){return <picture className={'v7-art '+className}><source media="(max-width: 700px)" srcSet={'/images/story-v7/'+name+'-760.webp'}/><img src={'/images/story-v7/'+name+'.webp'} alt={alt} width={name==='refund'?1400:1280} height={name==='refund'?933:name==='opening'?927:960} loading={eager?'eager':'lazy'} decoding="async" fetchPriority={eager?'high':'auto'}/></picture>}
function Action({href,onClick,children,secondary=false}){const props={className:'v7-action'+(secondary?' v7-secondary':''),...(href?{href}:{onClick,type:'button'})};const Tag=href?'a':'button';return <Tag {...props}>{children}<ArrowRight size={20}/></Tag>}
function Title({scene,index}){return <><div className="v7-eyebrow"><span>{String(index+1).padStart(2,'0')} / {scene.short}</span><i/><span>{scene.en}</span></div><h1 id="v7-title" tabIndex={-1}><span>{scene.title[0]}</span><em>{scene.title[1]}</em></h1></>}
function Rules(){return <div className="v7-rules"><h2>订单约定</h2><div><Clock3/><p><strong>≤ 120 秒</strong><span>数据新鲜度</span></p></div><div><Link2/><p><strong>标的匹配</strong><span>请求与响应</span></p></div><div><Database/><p><strong>≥ 100</strong><span>样本数量</span></p></div></div>}
function Receipt({refund=false,small=false}){return <article className={'v7-receipt'+(small?' compact':'')} aria-label={refund?'订单 B 的退款凭证示例':'订单 A 的付款凭证示例'}><div className="v7-receipt-top"><span>PUBLIC RECEIPT</span><span>交付示例</span></div><div className="v7-receipt-title"><h2>订单 {refund?'B':'A'}</h2><span className={'v7-payment-icon '+(refund?'is-refund':'is-payment')} aria-label={refund?'退款':'付款'}>{refund?<ArrowLeft size={25}/>:<Wallet size={25}/>}</span></div><dl><div><dt>来源签名</dt><dd className="v7-valid"><Check size={18}/>有效</dd></div><div><dt>零知识证明</dt><dd className="v7-proof"><Check size={18}/>有效</dd></div><div><dt>验收结果</dt><dd className={refund?'v7-return':'v7-valid'}>{refund?<Clock3 size={18}/>:<Check size={18}/>} {refund?'不合格':'合格'}</dd></div><div><dt>资金结果</dt><dd className={refund?'v7-return':'v7-valid'}>{refund?<ArrowLeft size={18}/>:<ArrowRight size={18}/>} {refund?'退还买方':'支付 Provider'}</dd></div></dl><div className={'v7-receipt-total '+(refund?'v7-return':'v7-valid')}><span>{refund?'退款依据已形成':'付款依据已形成'}</span><p><strong>0.002</strong><span>测试 ETH</span></p></div></article>}
function Opening({scene,index,go,closing=false}){return <><div className="v7-hero-layout"><div className="v7-copy"><Title scene={scene} index={index}/>{!closing&&<p className="v7-subtitle">VeilReceipt · 零知识验收凭证</p>}<p className="v7-body">{scene.body}</p><div className="v7-actions"><Action href={closing?'#/lab?scene=valid':undefined} onClick={()=>go(1)}>{closing?'运行真实验收':'开始这笔交易'}</Action><Action secondary href={closing?'#/receipts':'#/lab'}>{closing?'查看并核验凭证':'直接运行演示'}</Action></div></div><div className="v7-opening-art"><Art name="opening" eager alt="米白信封以陶土锁章封存，旁边是淡紫证明片和托管容器"/><div className={'v7-order-note '+(closing?'complete':'')}><span className="v7-note-icon">{closing?<Check size={19}/>:<Clock3 size={19}/>}</span><div><strong>订单 A</strong><small>{closing?'已结算 · 可复验':'等待验收'}</small></div></div><span className="v7-art-caption"><LockKeyhole size={18}/>私密交付</span>{closing&&<div className="v7-closing-result"><ShieldCheck size={23}/><p><b>验收合格 · Provider 已收款</b><span>签名、规则、证明与资金结果，保存在同一张凭证。</span></p></div>}</div></div>{closing?<div className="v7-conclusion-strip"><span><Fingerprint/>交付承诺</span><span><Braces/>验收规则</span><span><ShieldCheck/>验收结论</span><span><Wallet/>资金去向</span></div>:<Rules/>}</>}
function Dilemma({scene,index}){return <><div className="v7-compact-heading"><Title scene={scene} index={index}/><p className="v7-body">{scene.body}</p></div><div className="v7-dilemma"><article><span className="v7-section-label">路径 01</span><Eye size={30}/><h2>公开响应</h2><p>规则可以检查。<br/><strong>付费内容也被公开。</strong></p></article><div><Art name="opening" alt="同一份封存的付费行情数据"/><span>同一份付费数据</span></div><article><span className="v7-section-label">路径 02</span><FileCheck2 size={30}/><h2>只提交结论</h2><p>内容保持私密。<br/><strong>结论仍待独立验证。</strong></p></article></div><div className="v7-note"><Fingerprint size={19}/><p><b>Provider 签名认领交付。</b> 内容是否达标，仍需按约定规则核验。</p></div></>}
function Proof({scene,index}){return <><div className="v7-hero-layout"><div className="v7-copy"><Title scene={scene} index={index}/><p className="v7-body">{scene.body}</p><div className="v7-proof-formula"><span>私密数据 + 约定规则</span><ArrowRight size={22}/><b>验收证明</b></div><p className="v7-caption">买方持有原文，外部核验者检查证据。</p></div><Art name="proof" eager alt="信封与本地证明棱镜留在分界左侧，公开凭证位于右侧"/></div><div className="v7-boundaries"><article><LockKeyhole/><div><h2>保留私密</h2><p>请求、响应、随机盲因子</p></div><span>PRIVATE INPUT</span></article><article><ShieldCheck/><div><h2>公开验证</h2><p>订单、承诺、证明、验收结论</p></div><span>PUBLIC EVIDENCE</span></article></div></>}
function Diagram({kind,title,onExpand}){return <figure className={'v7-diagram v7-'+kind}><img src={'/images/story-v7/'+kind+'.webp'} width="1600" height="900" alt={title}/><button onClick={e=>onExpand(kind,title,e.currentTarget)} className="v7-expand"><Maximize2 size={17}/>放大图解</button></figure>}
function Flow({scene,index,onExpand}){const [step,setStep]=useState(0);return <><div className="v7-wide-heading"><div><Title scene={scene} index={index}/></div><p className="v7-body">{scene.body}</p></div><Diagram kind="flow" title="四角色服务泳道：私密交付留在买方，承诺、签名、证明进入合约；付款与退款分别流向 Provider 和买方" onExpand={onExpand}/><div className="v7-flow-controls"><label htmlFor="v7-step">逐步看消息流</label><select id="v7-step" value={step} onChange={e=>setStep(Number(e.target.value))}>{flow.map(([role,title],i)=><option key={role+title} value={i}>{String(i+1).padStart(2,'0')} / {title}</option>)}</select><span>私密交付</span><span>公共证据</span><span>资金流</span></div><div className="v7-flow-detail" aria-live="polite"><strong>{flow[step][0]}</strong><p>{flow[step][2]}</p></div><ol className="v7-flow-mobile">{flow.map(([role,title,body],i)=><li key={title}><span>{String(i+1).padStart(2,'0')}</span><div><b>{title}</b><small>{role}</small><p>{body}</p></div></li>)}</ol></>}
function Binding({scene,index,onExpand}){const [tech,setTech]=useState(0);return <><div className="v7-wide-heading"><div><Title scene={scene} index={index}/></div><p className="v7-body">{scene.body}</p></div><Diagram kind="binding" title="订单 A 的内容承诺和已锁定规则，连接 Poseidon2、Provider EIP-712 签名、Noir UltraHonk 证明与 Solidity 结算" onExpand={onExpand}/><div className="v7-tech-tabs" role="tablist" aria-label="技术机制">{technologies.map(([name,label,body,Icon],i)=><button role="tab" id={'v7-tech-'+i} aria-controls="v7-tech-panel" aria-selected={tech===i} tabIndex={tech===i?0:-1} key={name} onClick={()=>setTech(i)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;setTech(n);document.getElementById('v7-tech-'+n)?.focus();}}}><Icon size={19}/><span>{name}</span><small>{label}</small></button>)}</div><div className="v7-tech-description" id="v7-tech-panel" role="tabpanel" aria-labelledby={'v7-tech-'+tech}><p>{technologies[tech][2]}</p><b>签名在合约中验证，私密规则在电路中计算。</b></div></>}
function Outcome({scene,index,refund=false}){return <><div className="v7-outcome-layout"><div className="v7-copy"><Title scene={scene} index={index}/><p className="v7-body">{scene.body}</p><div className="v7-proof-badge"><ShieldCheck size={23}/>零知识证明有效</div><div className="v7-actions"><Action href={'#/lab?scene='+(refund?'stale':'valid')}>{refund?'运行退款演示':'运行付款演示'}</Action></div><p className="v7-caption">订单 {refund?'B · 过期':'A · 合格'}交付样例</p></div><div className="v7-receipt-stage"><Art eager name="opening" alt="同一份封存交付与托管资金，按订单约定完成验收"/><Receipt refund={refund}/></div></div><div className="v7-outcome-steps"><div><ShieldCheck/><p><b>证明有效</b><small>按约定规则完成计算</small></p></div><ArrowRight/><div>{refund?<Clock3/>:<Check/>}<p><b>验收{refund?'不合格':'合格'}</b><small>{refund?'这次响应已经过期':'这次响应满足条件'}</small></p></div><ArrowRight/><div>{refund?<ArrowLeft/>:<Wallet/>}<p><b>{refund?'退款':'付款'}确认</b><small>{refund?'买方收回托管款':'Provider 获得款项'}</small></p></div></div></>}
function Portable({scene,index}){const [changed,setChanged]=useState(false),[tested,setTested]=useState(false);return <><div className="v7-compact-heading"><Title scene={scene} index={index}/><p className="v7-body">{scene.body}</p></div><div className="v7-portable-layout"><div className="v7-portable-source"><span className="v7-section-label">01 / 导出原件</span><Receipt refund small/><p><Download size={17}/>同一张订单 B 凭证</p></div><div className="v7-verification-demo"><div className="v7-demo-heading"><ShieldCheck size={24}/><h2>独立核验</h2><span>原理演示</span></div><p>来源签名、订单规则、零知识证明与结算记录，共同支持这张凭证。</p><div className="v7-demo-controls"><button aria-pressed={!changed} onClick={()=>{setChanged(false);setTested(false)}}>原始凭证</button><button aria-pressed={changed} onClick={()=>{setChanged(true);setTested(false)}}>修改验收结果</button></div><dl className="v7-demo-fields"><div><dt>订单</dt><dd>B</dd></div><div><dt>验收结果</dt><dd className={changed?'v7-edited':''}>{changed?'合格':'不合格'}{changed&&<span>已修改</span>}</dd></div><div><dt>原始证明</dt><dd>保持不变</dd></div></dl><button className="v7-action" onClick={()=>setTested(true)}>核验这份{changed?'副本':'原件'}<ArrowRight size={18}/></button><div className={'v7-demo-result '+(tested?(changed?'rejected':'accepted'):'')} role="status">{tested?<>{changed?<X size={23}/>:<Check size={23}/>}<div><strong>{changed?'副本被拒绝':'原件核验通过'}</strong><p>{changed?'修改后的结论，与原始证明不一致。':'原始结论与证据保持一致。'}</p></div></>:<><FileCheck2 size={23}/><span>选择一份凭证，检查结论与证据的关系。</span></>}</div><a href="#/lab?scene=verify" className="v7-inline-link">用真实凭证复验<ArrowUpRight size={17}/></a></div></div></>}
function Commons({scene,index}){return <><div className="v7-compact-heading"><Title scene={scene} index={index}/><p className="v7-body">{scene.body}</p></div><div className="v7-commons"><div className="v7-toolbox"><span className="v7-section-label">已提供 / 可复用组件</span>{[[Braces,'验收电路','Noir'],[Wallet,'验证与结算','Solidity'],[FileCheck2,'公共凭证格式','公开证据'],[ShieldCheck,'独立核验工具','签名 · 证明 · 结算']].map(([Icon,name,tech])=><article key={name}><Icon/><h2>{name}</h2><span>{tech}</span><Check size={17}/></article>)}<p>原创代码采用 MIT 许可，支持修改与复用。</p></div><div className="v7-next-connections"><span className="v7-section-label">下一步 / 接入方向</span><h2>让更多 Agent，<br/>读懂交付证据。</h2><p>从订单 B 带出的凭证，成为其他应用可以检查的输入。</p><ul><li><Database/><span><b>真实 Provider</b>接入实际数据服务</span></li><li><Link2/><span><b>公共测试网</b>公开部署与验证</span></li><li><Fingerprint/><span><b>ERC-8004</b>适配公共信誉</span></li></ul><a className="v7-inline-link" href="#/protocol">查看技术说明<ArrowUpRight size={17}/></a></div></div></>}
export default function Story(){
 const [active,setActive]=useState(currentChapter),[zoom,setZoom]=useState(null);const modal=useRef(null),returnFocus=useRef(null),first=useRef(true);const scene=chapters[active];
 const go=i=>{location.hash='/story?chapter='+(i+1)};
 useEffect(()=>{const restoration=history.scrollRestoration;history.scrollRestoration='manual';const update=()=>{setActive(currentChapter());setZoom(null)};window.addEventListener('hashchange',update);return()=>{history.scrollRestoration=restoration;window.removeEventListener('hashchange',update)}},[]);
 useEffect(()=>{document.title='VeilReceipt · '+scene.short;window.scrollTo({top:0,behavior:'instant'});if(!first.current)document.getElementById('v7-title')?.focus({preventScroll:true});first.current=false},[active]);
 useEffect(()=>{if(zoom){modal.current?.showModal()}else if(modal.current?.open){modal.current.close();returnFocus.current?.focus()}},[zoom]);
 function expand(kind,title,trigger){returnFocus.current=trigger;setZoom({kind,title})}function closeZoom(){setZoom(null)}
 const content={0:<Opening scene={scene} index={active} go={go}/>,1:<Dilemma scene={scene} index={active}/>,2:<Proof scene={scene} index={active}/>,3:<Flow scene={scene} index={active} onExpand={expand}/>,4:<Binding scene={scene} index={active} onExpand={expand}/>,5:<Outcome scene={scene} index={active}/>,6:<Outcome scene={scene} index={active} refund/>,7:<Portable scene={scene} index={active}/>,8:<Commons scene={scene} index={active}/>,9:<Opening scene={scene} index={active} go={go} closing/>}[active];
 return <div className="v7-story" data-tone={scene.tone} data-chapter={active+1} onKeyDown={e=>{if(zoom||e.target.closest('button,a,input,select,textarea,[role=tab]'))return;if(e.key==='ArrowRight'&&active<9){e.preventDefault();go(active+1)}if(e.key==='ArrowLeft'&&active>0){e.preventDefault();go(active-1)}}}>
 <nav className="v7-chapters" aria-label="介绍章节"><div className="v7-chapter-desktop">{chapters.map((c,i)=><button key={c.short} aria-current={active===i?'step':undefined} aria-label={'第 '+(i+1)+' 章：'+c.short} onClick={()=>go(i)}><span>{String(i+1).padStart(2,'0')}</span><small>{c.short}</small></button>)}<span className="v7-rail-foot">10<br/>CHAPTERS</span></div><div className="v7-chapter-mobile"><label htmlFor="v7-chapter-select">项目介绍</label><select id="v7-chapter-select" value={active} onChange={e=>go(Number(e.target.value))}>{chapters.map((c,i)=><option key={c.short} value={i}>{String(i+1).padStart(2,'0')} / {c.short}</option>)}</select><span>{String(active+1).padStart(2,'0')} / 10</span></div></nav>
 <section className={'v7-scene v7-scene-'+(active+1)} aria-labelledby="v7-title" key={active}><div className="v7-content">{content}</div><div className="v7-bridge"><p>{scene.bridge}</p><div>{active>0&&<button className="v7-back" onClick={()=>go(active-1)} aria-label="上一章"><ArrowLeft size={19}/></button>}<button onClick={()=>go(active<9?active+1:0)}>{scene.next}<ArrowRight size={19}/></button></div></div></section>
 <dialog className="v7-zoom" ref={modal} aria-labelledby="v7-zoom-title" onCancel={closeZoom} onClick={e=>{if(e.target===e.currentTarget)closeZoom()}}><div><header><h2 id="v7-zoom-title">{zoom?.kind==='flow'?'完整服务泳道':'订单与证据绑定'}</h2><button onClick={closeZoom} aria-label="关闭放大图解"><X size={23}/></button></header>{zoom&&<div className="v7-zoom-scroll"><img src={'/images/story-v7/'+zoom.kind+'.webp'} alt={zoom.title}/></div>}<p>图解可横向滚动 · 按 Esc 关闭</p></div></dialog>
 </div>
}
