import React,{useRef} from 'react';
import {FileCheck2,ShieldCheck,Upload,Download,ArrowRight,LoaderCircle,AlertTriangle} from '../icons';
import {useSession} from '../session';
import {checkLabels} from '../model';
import {Kicker,CheckItem} from './Common';
export default function Verifier(){
 const s=useSession(),file=useRef(null);const original=s.base||s.receipt||s.state?.receipts[0];
 async function upload(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>100000){s.setNotice('凭证超过 100 KB，请选择本项目导出的 JSON。');return}try{const value=JSON.parse(await f.text());if(!value||typeof value!=='object'||Array.isArray(value))throw Error();await s.verify(value,`导入原件 · ${f.name}`)}catch{s.setNotice('文件不是有效的 JSON 凭证。')}}
 function downloadOriginal(){if(!original)return;const url=URL.createObjectURL(new Blob([JSON.stringify(original,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;const id=/^[0-9]+$/.test(String(original.orderId))?original.orderId:'imported';link.download=`veilreceipt-${id}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const result=s.verification;
 return <div className="verifier-grid"><section className="evidence-source"><Kicker>PORTABLE RECEIPT</Kicker><h2>一份原件。<br/>一次公开的挑战。</h2><p>保留签名与证明，只改动验收结果。<br/>看看核验器是否接受这份副本。</p><div className="artifact-label"><FileCheck2 size={26}/><div><strong>{original?`订单 #${String(original.orderId||'未知').padStart(4,'0')}`:'尚无凭证'}</strong><span>{s.candidateName||'选择最近的真实凭证，或导入自己的原件。'}</span></div></div><div className="button-stack"><button className="action" disabled={!original||s.checking||s.connection!=='online'} onClick={()=>s.verify(original,'原始凭证 · 未修改')}><ShieldCheck size={18}/>核验原始凭证<ArrowRight size={18}/></button><button className="action secondary" onClick={()=>file.current?.click()} disabled={s.checking}><Upload size={18}/>导入凭证 JSON</button><input ref={file} hidden type="file" accept=".json,application/json" aria-label="凭证 JSON 文件" onChange={upload}/></div><button className="tamper-action" disabled={!original||s.checking||s.connection!=='online'} onClick={s.tamper}>修改结果，再核验一次<ArrowRight size={19}/></button>{original&&<button className="text-action" onClick={downloadOriginal}><Download size={17}/>下载当前原始凭证</button>}<p className="small-note">文件中的地址不能替换核验器的可信部署。<br/>篡改只发生在副本，原始结算不会改变。</p></section><section className={`verification-paper ${result&&!result.valid?'invalid':''}`} aria-live="polite" aria-busy={s.checking}><div className="receipt-top"><span>INDEPENDENT VERIFICATION</span>{s.checking?<LoaderCircle className="spin" size={23}/>:<ShieldCheck size={23}/>}</div><h2>{s.checking?'正在核验':result?.unavailable?'核验暂不可用':result?(result.valid?'凭证有效':'凭证被拒绝'):'等待证据'}</h2><p>{result?.unavailable?'服务连接异常。尚未获得本次核验结论。':result?(result.valid?'签名、规则、证明与链上结算一致。':'当前文件未通过核验，不能作为有效交付证据。'):'来源、规则、证明与结算，需要相互一致。'}</p><div className="check-list">{result?.checks.map((c,i)=><CheckItem key={i} check={c} label={checkLabels[c.name]||c.name}/>)}{!result&&Object.entries(checkLabels).slice(0,8).map(([key,label],i)=><div className="pending-check" key={key}><span>0{i+1}</span>{label}<span>待核验</span></div>)}</div>{result&&!result.valid&&!result.unavailable&&<div className="rejection-note"><AlertTriangle size={19}/><span>公开结论不能脱离原始证明被改写。</span></div>}<details><summary>查看核验器信任锚</summary><p>本演示从当前本地部署固定合约地址，读取本地 EVM；不是独立公共节点。</p><code>{s.state?.network.escrow||'等待本地服务'}</code><p>命令行核验可在独立进程运行，RPC 和合约须由核验者另行确认。</p></details></section></div>
}
